import React,{useMemo,useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,Briefcase,ChevronRight,Download,ExternalLink,FileText,Image as ImageIcon,Mail,MapPin,Menu,Play,Search,Video,X,Plus,Copy,CheckCircle2,Code2,CircuitBoard,Factory,GraduationCap} from 'lucide-react';
import {posts} from './content/posts';
import './styles.css';

const products=[
 {title:'PLC Training Platform',category:'Automation',image:'/assets/10438.jpg',summary:'Controller programming, hardware I/O, wiring and practical troubleshooting.'},
 {title:'Digital Electronics Trainer',category:'Electronics',image:'/assets/10443.jpg',summary:'Experiment-oriented platform for logic systems and digital circuits.'},
 {title:'Embedded Systems Trainer',category:'Embedded',image:'/assets/10446.jpg',summary:'Microcontroller, sensor interfacing and applied embedded experiments.'},
 {title:'Instrumentation Trainer',category:'Measurement',image:'/assets/10441.jpg',summary:'Practical measurement, sensors and signal-conditioning activities.'},
 {title:'Industrial Control Panel',category:'Automation',image:'/assets/10449.jpg',summary:'Motor control, protection, PLC integration and industrial wiring.'},
 {title:'Renewable Energy Trainer',category:'Renewable',image:'/assets/10450.jpg',summary:'Solar measurement, power conversion and renewable-energy experiments.'}
];
const skills=[['PLC & Automation',['Siemens LOGO!','Delta PLC','WPLSoft','HMI','Field wiring']],['Embedded Systems',['Arduino','STM32','ESP32','ESP8266','PIC']],['Electronics & PCB',['Proteus','LTspice','EasyEDA','PCB design','Testing']],['Documentation',['User manuals','Experiment guides','Wiring diagrams','QR documentation']],['Manufacturing',['PCB assembly','Trainer assembly','Inspection','Production support']],['Visual Tools',['Microsoft Office','Photoshop','Illustrator','Premiere Pro']]];
const institutes=['Chapai Nawabganj Polytechnic Institute','Dinajpur Polytechnic Institute','Rangpur Polytechnic Institute','Shariatpur Polytechnic Institute','Sweden Polytechnic Institute','PFI / Navy Base, Kaptai','Sirajganj Polytechnic Institute','Jashore Polytechnic Institute','Satkhira Polytechnic Institute'];

function useHash(){const [hash,setHash]=useState(location.hash||'#home');useEffect(()=>{const h=()=>setHash(location.hash||'#home');addEventListener('hashchange',h);return()=>removeEventListener('hashchange',h)},[]);return hash}
function Header(){const [open,setOpen]=useState(false);return <header><div className="nav"><a href="#home" className="brand"><span>SS</span><div><b>Sabbir Shehab</b><small>Assistant Engineer</small></div></a><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{['About','Experience','Work','Journal','Manuals','Training','Skills','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setOpen(false)}>{x}</a>)}<a className="cv" href="/cv/Sabbir_Ahmmed_Shehab_Assistant_Engineer_CV.pdf" download><Download size={16}/> Download CV</a></nav></div></header>}
function Hero(){return <section id="home" className="hero"><div className="grid-bg"/><div className="wrap hero-grid"><div><div className="eyebrow">ASSISTANT ENGINEER · PRODUCT DEVELOPMENT</div><h1>I turn engineering concepts into <em>working products, manuals and practical training.</em></h1><p>Electronics, embedded systems, PLC automation and educational trainer development—supported from design and manufacturing through documentation and knowledge transfer.</p><div className="actions"><a className="primary" href="#work">View selected work <ChevronRight/></a><a className="secondary" href="#journal"><BookOpen/> Read journal</a></div><div className="stats"><div><strong>2022</strong><span>Engineering career started</span></div><div><strong>9+</strong><span>Training institutions</span></div><div><strong>End-to-end</strong><span>Product lifecycle exposure</span></div></div></div><div className="portrait"><img src="/assets/profile.png"/><div className="float f1"><CircuitBoard/> Build<br/><small>Practical systems</small></div><div className="float f2"><FileText/> Document<br/><small>Experiment manuals</small></div><div className="availability">AVAILABLE FOR ENGINEERING OPPORTUNITIES<br/><b>Dhaka, Bangladesh</b></div></div></div></section>}
function About(){return <section id="about" className="section"><div className="wrap"><div className="section-head"><span>01 / PROFILE</span><div><div className="eyebrow">ENGINEERING PROFILE</div><h2>Practical engineering ownership—not just task execution.</h2></div></div><div className="two-col"><div><p className="lead">I work where product development, manufacturing and technical education meet.</p><p>Since 2022, I have supported educational and industrial trainer systems across electronics, electrical engineering, embedded systems, automation, networking and robotics.</p><p>My contribution extends beyond hardware: I create experiment-oriented manuals, wiring guidance and QR-linked resources, then help users operate and troubleshoot the final systems.</p></div><div className="cap-list">{[['Product engineering','Requirement to validated hardware'],['Technical documentation','Clear manuals and experiment workflows'],['Manufacturing support','Assembly, testing and quality checks'],['Knowledge transfer','Training, demonstrations and troubleshooting']].map((x,i)=><div key={x[0]}><span>0{i+1}</span><b>{x[0]}</b><small>{x[1]}</small></div>)}</div></div></div></section>}
function Experience(){return <section id="experience" className="section soft"><div className="wrap"><div className="eyebrow">CAREER JOURNEY</div><h2>Engineering growth through real products.</h2><div className="timeline">{[['2022','Joined Fabotronix','Started practical work in trainer development, electronics and production support.'],['2023','Service engineering exposure','Worked with pumps, motors and home-appliance troubleshooting at Gazi International.'],['2024','Documentation systems','Expanded experiment manuals, wiring guidance and QR-linked technical resources.'],['2025','Training & automation','Supported PLC, embedded and trainer-based technical sessions across institutions.'],['2026','Assistant Engineer','Product development, automation, documentation and manufacturing support.']].map((x,i)=><div className="time" key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]}</p></div></div>)}</div></div></section>}
function Work(){const [filter,setFilter]=useState('All');const cats=['All',...new Set(products.map(p=>p.category))];return <section id="work" className="section"><div className="wrap"><div className="split-title"><div><div className="eyebrow">SELECTED WORK</div><h2>Engineering systems and product workflows.</h2></div><p>Representative work across automation, electronics, embedded systems and technical learning equipment.</p></div><div className="filters">{cats.map(c=><button className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="cards">{products.filter(p=>filter==='All'||p.category===filter).map(p=><article className="product"><img src={p.image}/><div><small>{p.category}</small><h3>{p.title}</h3><p>{p.summary}</p><a href="#contact">Discuss this work <ChevronRight size={16}/></a></div></article>)}</div></div></section>}
function Journal(){const [q,setQ]=useState('');const [cat,setCat]=useState('All');const categories=['All',...new Set(posts.map(p=>p.category))];const filtered=useMemo(()=>posts.filter(p=>(cat==='All'||p.category===cat)&&(`${p.title} ${p.excerpt} ${p.tags.join(' ')}`.toLowerCase().includes(q.toLowerCase()))),[q,cat]);return <section id="journal" className="section journal"><div className="wrap"><div className="split-title"><div><div className="eyebrow">ENGINEERING JOURNAL</div><h2>Articles, pictures, videos and downloadable resources.</h2></div><p>A growing knowledge hub for product development, PLC, electronics, documentation, manufacturing and GIS.</p></div><div className="journal-tools"><label><Search/><input placeholder="Search articles, tags or topics" value={q} onChange={e=>setQ(e.target.value)}/></label><div className="filters">{categories.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div></div><div className="post-grid">{filtered.map(p=><a className="post-card" href={'#post/'+p.slug}><img src={p.image}/><div><small>{p.category} · {p.readTime}</small><h3>{p.title}</h3><p>{p.excerpt}</p><span>Read article <ChevronRight size={16}/></span></div></a>)}</div><div className="studio-callout"><div><Plus/><div><h3>Post Composer included</h3><p>Create a structured article with text, images and YouTube video links, then copy the generated post data into the website.</p></div></div><a className="secondary" href="#studio">Open Post Composer</a></div></div></section>}
function Article({slug}){const p=posts.find(x=>x.slug===slug);if(!p)return <main className="section wrap"><h2>Article not found</h2></main>;return <main className="article"><div className="article-hero wrap"><a href="#journal">← Engineering Journal</a><div className="eyebrow">{p.category}</div><h1>{p.title}</h1><p>{p.excerpt}</p><div className="meta">{p.date} · {p.readTime}</div><img src={p.image}/></div><div className="article-body">{p.body.map((b,i)=>b.type==='heading'?<h2 key={i}>{b.text}</h2>:b.type==='paragraph'?<p key={i}>{b.text}</p>:b.type==='list'?<ul key={i}>{b.items.map(x=><li>{x}</li>)}</ul>:<figure key={i}><img src={b.src}/><figcaption>{b.caption}</figcaption></figure>)}{p.video&&<div className="video"><iframe src={p.video} title={p.title} allowFullScreen/></div>}<div className="tags">{p.tags.map(t=><span>{t}</span>)}</div></div></main>}
function Manuals(){return <section id="manuals" className="section soft"><div className="wrap manuals"><div><div className="eyebrow">TECHNICAL DOCUMENTATION</div><h2>Documentation engineered for actual use.</h2><p className="lead">A trainer is only complete when users can understand, connect, experiment and troubleshoot it correctly.</p><p>I develop user manuals and experiment guides covering safety, system overview, panel connection, circuit diagrams, operating procedures, observations and troubleshooting.</p><div className="feature-grid">{['Experiment-oriented structure','Wiring and circuit guidance','QR-linked digital access','Troubleshooting support'].map(x=><div><CheckCircle2/>{x}</div>)}</div></div><div className="manual-visual"><img src="/assets/manuals-folder.png"/><img src="/assets/profile.png"/></div></div></section>}
function Training(){return <section id="training" className="section"><div className="wrap"><div className="split-title"><div><div className="eyebrow">KNOWLEDGE TRANSFER</div><h2>Technical training across Bangladesh.</h2></div><p>Trainer operation, software, wiring, troubleshooting and experiment demonstrations.</p></div><div className="training"><div className="radar"><b>BD</b><span>TRAINING FOOTPRINT</span>{[1,2,3,4,5,6].map(i=><i style={{transform:`rotate(${i*58}deg) translateY(-105px)`}}/>)}</div><div className="institutes">{institutes.map((x,i)=><div><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b><ChevronRight/></div>)}</div></div></div></section>}
function Skills(){return <section id="skills" className="section soft"><div className="wrap"><div className="eyebrow">TECHNICAL CAPABILITY</div><h2>Tools supported by practical application.</h2><div className="skill-grid">{skills.map(([n,items],i)=><div><div className="skill-icon">{[<CircuitBoard/>,<Code2/>,<Briefcase/>,<FileText/>,<Factory/>,<ImageIcon/>][i]}</div><h3>{n}</h3><div className="tags">{items.map(x=><span>{x}</span>)}</div></div>)}</div></div></section>}
function Composer(){const [title,setTitle]=useState('');const [category,setCategory]=useState('Product Development');const [excerpt,setExcerpt]=useState('');const [image,setImage]=useState('/assets/10438.jpg');const [video,setVideo]=useState('');const [body,setBody]=useState('Write your article here...');const [copied,setCopied]=useState(false);const slug=title.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');const output=JSON.stringify({slug,title,excerpt,category,date:new Date().toISOString().slice(0,10),readTime:'5 min read',image,tags:[],video,body:[{type:'paragraph',text:body}]},null,2);const copy=()=>{navigator.clipboard.writeText(output);setCopied(true);setTimeout(()=>setCopied(false),1500)};return <main id="studio" className="section studio"><div className="wrap"><a href="#journal">← Back to Journal</a><div className="eyebrow">CONTENT STUDIO</div><h1>Engineering Post Composer</h1><p>This composer creates the structured content block used by Version 3. Pictures can be local website assets or hosted image URLs. Videos should normally use YouTube embed links.</p><div className="composer"><div className="form"><label>Article title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>Product Development</option><option>PLC & Automation</option><option>Electronics</option><option>Technical Documentation</option><option>GIS & Remote Sensing</option><option>Career</option></select></label><label>Short summary<textarea value={excerpt} onChange={e=>setExcerpt(e.target.value)}/></label><label>Cover image path or URL<input value={image} onChange={e=>setImage(e.target.value)}/></label><label>YouTube embed URL<input value={video} onChange={e=>setVideo(e.target.value)} placeholder="https://www.youtube.com/embed/..."/></label><label>Article text<textarea rows="10" value={body} onChange={e=>setBody(e.target.value)}/></label></div><div className="output"><div className="preview"><img src={image}/><small>{category}</small><h2>{title||'Article title preview'}</h2><p>{excerpt||'Your article summary will appear here.'}</p>{video&&<div className="video-badge"><Video/> Video included</div>}</div><pre>{output}</pre><button className="primary" onClick={copy}>{copied?<CheckCircle2/>:<Copy/>}{copied?'Copied':'Copy post data'}</button></div></div><div className="note"><b>Publishing workflow:</b> paste the copied object into <code>src/content/posts.js</code>, add a comma after the previous post, commit through GitHub Desktop and push. Cloudflare will redeploy automatically.</div></div></main>}
function Contact(){return <section id="contact" className="contact"><div className="wrap contact-grid"><div><div className="eyebrow">LET’S CONNECT</div><h2>Looking for an engineer who can build, document and support real products?</h2><p>I am interested in product development, electronics, automation, technical documentation, manufacturing and engineering-support opportunities.</p><div className="actions"><a className="light" href="mailto:sabbir.fabotronix@gmail.com"><Mail/> Send Email</a><a className="dark-outline" href="/cv/Sabbir_Ahmmed_Shehab_Assistant_Engineer_CV.pdf" download><Download/> Download CV</a></div></div><div className="contact-card"><div><Mail/><span>EMAIL<b>sabbir.fabotronix@gmail.com</b></span></div><div><MapPin/><span>LOCATION<b>Dhaka, Bangladesh</b></span></div><div><Briefcase/><span>TARGET ROLES<b>Electronics · Automation · Product Engineering</b></span></div></div></div><footer>© 2026 Sabbir Ahmmed Shehab <span>Assistant Engineer · Engineering Portfolio & Journal</span></footer></section>}
function App(){const hash=useHash();if(hash.startsWith('#post/'))return <><Header/><Article slug={hash.replace('#post/','')}/><Contact/></>;if(hash==='#studio')return <><Header/><Composer/><Contact/></>;return <><Header/><Hero/><About/><Experience/><Work/><Journal/><Manuals/><Training/><Skills/><Contact/></>}
createRoot(document.getElementById('root')).render(<App/>);
